# Generated by Django 4.0.6 on 2022-08-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0002_account_currency_receipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='cardStatus',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='pin',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='signature',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
