# Generated by Django 4.0.6 on 2022-08-19 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0004_customer_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='receipt',
        ),
    ]
